# Generated by Django 5.0.7 on 2024-09-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
